services:

  mysql:
    image: mysql:8.0
    container_name: hrsystem_mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pessystem

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  frontend:
    build:
      context: .
      dockerfile: src/frontend/Dockerfile.frontend

    container_name: hrsystem_frontend

    ports:
      - "5173:5173"

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - backend

    restart: unless-stopped


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend

    container_name: hrsystem_backend

    ports:
      - "3000:3000"

    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: pessystem
      JWT_SECRET: hr_secret

    depends_on:
      mysql:
        condition: service_healthy

    restart: unless-stopped


  phpmyadmin:
    image: phpmyadmin:latest
    container_name: hrsystem_phpmyadmin

    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

    ports:
      - "8081:80"

    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: